[package]
name = "zkcoins-program-plonky2"
version = "0.0.1"
edition = "2021"

[dependencies]
plonky2 = "1.1.0"
anyhow = "1.0"
num = "0.4"
serde = { workspace = true }
bincode = { workspace = true }
itertools = { version = "0.11", default-features = false, features = ["use_alloc"] }

[dev-dependencies]
num-bigint = "0.4"
num-traits = "0.2"
sha2 = { workspace = true }
shared = { path = "../shared" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage_nightly)"] }
